
const Footer = () => {

    return(
        <div className="">
            
PLANOS TARIFÁRIOS	SERVIÇOS	PRODUTOS	UNITEL T+
UNITELT+ PLAY	SERVIÇOS ADICIONAIS	TELEMÓVEIS E SMARTPHONES	QUEM SOMOS
TARIFÁRIO CLÁSSICO	SERVIÇOS DE SMS	PLACAS 3G E ROUTERS	LOJAS
TARIFÁRIO PRESTIGIO	RECARGA ONLINE	TABLETES E PORTATEIS	PROMOÇOES
TARIFÁRIO EMPRESA	RECARREGAMENTOS	TELEFONES	REVISTA UNITE T+
TARIFÁRIO LIBERTY	T+ FAMILY	 	RECRUTAMENTO
FIXO +	ROAMING	 	VIDEOS UNITELT+
 	PORTABILIDADE	 	CONTACTE-NOS
 	MEGAS LIVRES
        </div>
    );
    
}
export default Footer;

